### ISSUE TITLE
Small correction to INSTALL file

### ISSUE THREAD

**Issue by theindigamer** [openkim/kim-api#1]
In the `INSTALL` file, between 

```
$ sudo make install
$ sudo make install-set-default-to-vX  # replace X with the major version of this package
```

and `./vc_forces_numer_deriv`, there should be a line with `ldconfig`. Otherwise one might get the following issue:

```
./vc_forces_numer_deriv: error while loading shared libraries: libkim-api-v1.so : cannot open shared object file: No such file or directory
```

See comments on the question http://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s

**Comment by ellio167** [comment]
Thanks for the note.  You are correct, an `sudo ldconfig` should be added.  I'll do this and it will be in the next push to github.

However, the situation is more complex.  If you are using a ubuntu system, this is sufficient.  However, if you are using a Redhat-like system (centos, etc.) the default setting do not include /usr/local/lib in the ld.so.config.  So, this must be added first (see section 3.2 of http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html).
