### ISSUE TITLE
kim-api-v2-collections-management does not work properly

### ISSUE THREAD

**Issue by dschopf** [openkim/kim-api#20]
When running kim-api-v2-collections-management from the kim-api-v2-2.0.0-beta.3 package I get the following error:
```
$ kim-api-v2-collections-management install system --sudo EAM_Dynamo_AcklandBaconCalder_1997_Fe__MO_142799717516_005
Enter Password : 
/usr/bin/kim-api-v2-collections-management: line 105: test: 2: unary operator expected
*** ERROR *** EAM_Dynamo_AcklandBaconCalder_1997_Fe__MO_142799717516_005 found at openkim.org is not compatible with this version of the KIM API.

Aborting!
```

This seems to be related to an empty line 38, which simply says 
```
major_version=
```
Apparently the cmake macro @PROJECT_VERSION_MAJOR@ is not properly evaluated.

I use this cmake command:
```
  cmake ../kim-api-v2-2.0.0-beta.3 \
  	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX="/usr" \
	-DCMAKE_INSTALL_LIBDIR="lib" \
	-DCMAKE_INSTALL_LIBEXECDIR="/usr/lib" \
	-DKIM_API_BUILD_EXAMPLES=ON
```
and cmake version 3.13.3.

**Comment by ellio167** [comment]
Hi, Thanks for your report.  Indeed, this was also reported on the openkim mailing list

https://groups.google.com/d/msg/openkim/a6tq-QF2CVA/bUR0MWyTCAAJ

The issue is fixed commit cd35405a5f1874f529639f6cf8c115b2560d227e which is currently available on the 'devel-v2' branch.
