### ISSUE TITLE
Collections management truncates labels

### ISSUE THREAD

**Issue by dskarls** [openkim/kim-api#21]
Using v2.0.2 tarball release, doing `kim-api-collections-management list` is producing the following output format in with GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu), although the bash version shouldn't be important:
```bash
...
User Collection
-------------------------------------------------------------------------------
Model: '/home/openkim/.kim-api/model-drivers-dir' 
	EAM_CubicNaturalSpline__MD_853402641673_002
	EDIP__MD_506186535567_002
	Tersoff_LAMMPS__MD_077075034781_003

Models: '/home/openkim/.kim-api/models-dir' 
	EAM_CubicNaturalSpline_ErcolessiAdams_1994_Al__MO_800509458712_002
	EDIP_JustoBazantKaxiras_1998_Si__MO_958932894036_002
	Tersoff_LAMMPS_ErhartAlbe_2005_SiC__MO_903987585848_003
	Tersoff_LAMMPS_Tersoff_1988_C__MO_579868029681_002

Simulator: '/home/openkim/.kim-api/simulator-models-dir'
	Sim_LAMMPS_MEAM_JelinekGrohHorstemeyer_2012_AlSiMgCuFe__SM_656517352485_000
...
```
Notice it just says "Model:" and "Simulator:" instead of "Model Drivers" and "Simulator Models", respectively.  The problem is that there are double quotes missing in the print_collection_item_list() function when processing its first argument:
https://github.com/openkim/kim-api/blob/44495c2a17f42bea72e60a0d58b12b176dd16f4a/utils/collections-management.in#L569
This results in dropping the space and everything afterward in the strings "Model Drivers" and "Simulator Models".  This line just needs to be
```
   local item_label="$1"
```

**Comment by ellio167** [comment]
Thanks @dskarls.

Actually, already fixed in 3b83826832910bd0ac9c973839e1164eee41c828
