### ISSUE TITLE
Is it possible to use openMP inside a model driver written in Fortran? 

### ISSUE THREAD

**Issue by meTchaikovsky** [openkim/kim-api#23]
In a model driver I wrote in Fortran, I want to use OpenMP to run some regions in parallel. (I can't use MPI because of the nature of the model)
To do so, I just encapsulated the regions with 

`!$OMP PARALLEL DEFAULT(shared)`
 `!$OMP DO`

  some code block in model_driver.F90

 `!$OMP END DO`
 `!$OMP END PARALLEL`

However, when I use the installed parameterized model for computing the energy and forces of a structure, the CPU usage is no more than 100%.

The input script for lammps is 

`units metal`
`atom_style atomic`
`read_data new.lmp`
`pair_style kim nn_li3n`
`pair_coeff  * * Li N`
`neighbor       0 bin`
`neigh_modify   delay 0 every 1 check yes`
`dump force all custom 1 f_lammps.txt id fx fy fz`
`run 0`

I built lammps with `cmake`
`cmake -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -D CMAKE_Fortran_COMPILER=gfortran -D PKG_KIM=on -D PKG_USER-OMP=yes -D BUILD_OMP=yes -D KIM_LIBRARY=$the_path -D KIM_INCLUDE_DIR=$the_path ../cmake`

I ran lammps with command 

`env OMP_NUM_THREADS=4 lmp < in.input `

The first two lines of the output is 

`LAMMPS (15 May 2019)`
`  using 4 OpenMP thread(s) per MPI task`

**Comment by ellio167** [comment]
It should be possible, but we really haven't tried this sort of thing at this point.

To make it work, the first thing I would try is to adjust the build behavior for when your model driver is being built and installed.  You will need to do this without using the `kim-api-collections-management` utility.  Instead, from your model driver source directory do something like:

```
mkdir build
cd build
cmake .. -D<appropriate omp compiler parameters>
make
make install
```
try this and let us know what works or if you get stuck.

**Comment by meTchaikovsky** [comment]
Because I'm pretty new to `cmake` and `lammps`, I don't know what `omp compiler parameters ` to set ......

Here is what I have tried: 

1. I add this code block to `CMakeLists.txt` right after `# End preamble`

```
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "-fopenmp")
    set (CMAKE_CXX_FLAGS "-fopenmp")
endif()
```

The original `CMakeLists.txt` was:
```
cmake_minimum_required(VERSION 3.4)

list(APPEND CMAKE_PREFIX_PATH $ENV{KIM_API_CMAKE_PREFIX_DIR})
find_package(KIM-API 2.0 REQUIRED CONFIG)
if(NOT TARGET kim-api)
  enable_testing()
  project("${KIM_API_PROJECT_NAME}" VERSION "${KIM_API_VERSION}"
    LANGUAGES CXX C Fortran)
endif()
# End preamble


set(MODEL_DRIVER_NAME "driver")

add_kim_api_model_driver_library(
  NAME                    ${MODEL_DRIVER_NAME}
  CREATE_ROUTINE_NAME     "model_driver_create_routine"
  CREATE_ROUTINE_LANGUAGE "fortran"
  )

target_sources(${MODEL_DRIVER_NAME} PRIVATE
  ${MODEL_DRIVER_NAME}.F90
  char_zeta.F90
  neuralnetwork.F90
  )
```

2. After I changed `CMakeLists.txt`, I installed the model driver (which is written in only Fortran) with 
```
mkdir build 
cd build 
cmake .. 
make 
make install 
```

3. Then I installed the parameterized model in the same way (without using `kim-api-collections-management`).

To see whether it works, I added a small code block inside subroutine `Compute_Energy_Forces` which computes the energy and forces given a structure (a subroutine of driver.F90)

```
!$OMP PARALLEL 
!$omp DO
  do aux_ind = 1, 100
    write(aux_char, '(a, i5, a, i5, a, i5)') &
      'here', aux_ind, 'thread_num', omp_get_thread_num(), 'total', omp_get_num_threads()
    call kim_log_entry(model_compute_arguments_handle, & 
      kim_log_verbosity_error, aux_char)
  end do 
!$omp end do 
!$OMP END PARALLEL 
```

With the same `lammps` input script, I ran `env OMP_NUM_THREADS=4 lmp < in.input`. However, from the output, the total number of threads is still 1. 

Why the driver is not aware of the variable `OMP_NUM_THREADS `?

**Comment by meTchaikovsky** [comment]
I solved this problem by adding `-fopenmp` flag to `Fortran_FLAGS` in file `${path_to_driver_dir}/build/CMakeFiles/driver.dir/flags.make` right after `cmake ..` by using the above `CMakeLists.txt`.

**Comment by ellio167** [comment]
Hi @meTchaikovsky, I'm glad you found a way to make it work.

More generally, based on the details you provided above, I think you could use this sequence of commands (which would be a more "standard" way to do it):

```
mkdir build 
cd build 
cmake .. -DCMAKE_Fortran_FLAGS=-fopenmp
make 
make install 
```

Cheers,

Ryan
