### ISSUE TITLE
Is there a native way to get the 'actual' ids of neighbor atoms?

### ISSUE THREAD

**Issue by meTchaikovsky** [openkim/kim-api#24]
In the model driver I created with `kim-api`, I need to get the 'actual' ids of neighbor atoms. What I mean by 'actual' ids is:

Assume there are 10 atoms in a periodic (in all three directions) simulation box, a copy of atom 2 is a neighbor of atom 1 within a cutoff. Since this copy of atom 2 is considered a 'ghost atom', the returned index is not 2 when I call 

```
call kim_get_neighbor_list(& 
  model_compute_arguments_handle, 1, 1, num_n, & 
  neighbors_of_particle, ierr)
```

Is there a Fortran subroutine that gives the actual ids of neighbors of an atom? If there is not, is there a subroutine that returns the lattice parameters of the current simulation box?

**Comment by ellio167** [comment]
This information is not available and not even necessarily well defined.  The kim-api does not expect or require that the non-contributing particles are associated with periodic boundary conditions (BC).  In fact, the BCs used to generate non-contributing particles could be anything at all.  It cannot matter to the model driver (assuming it is implemented correctly).

Can you describe the computation you are trying to perform and how the "actual ids" of the neighbor atoms would be used?

**Comment by meTchaikovsky** [comment]
Hi, 
in the model driver I created, I'm using neural networks for computing energy contributions of each atom in the simulation box. The sum of energy contributions is considered potential energy. 

The input to a neural network for computing the energy contribution of a center atom is an atomic descriptor describing its local atomic environment. The atomic descriptor of the center atom is a function of the relative positions of its neighbors with itself.

To compute the force acts at an atom within the simulation box in the x-direction, I need to take the partial derivate of potential energy w.r.t the x coordinate of the atom. From the description above, since the potential energy is a sum of energy contributions, I need to find the energy contributions that are affected by this x coordinate, which means

**I need to find the set of neighbors (no duplicates) whose atomic descriptor is affected by this center atom. And the set of neighbors should be indexed correctly.**

After I found such neighbors, I can use the atomic descriptors of these neighbors (**This explains why the neighbors should be indexed correctly, because the atomic descriptors of atoms in the simulation box is computed in the first place, a correct index is required to slice the correct atomic descriptor**) to compute how each energy contribution changes w.r.t each atomic descriptor. Then, combined with how each atomic descriptor changes w.r.t the x coordinate of the center atom, I can compute the force acts at the center atom in the x-direction.

Since a copy of atom 2 (**with an index other than 2**) could be a neighbor of atom 1 while the actual atom 2 is not (**2 is not in the list of neighbors of atom 1**), this causes a problem when I compute the force acts at atom 1. Because 2 is not in its neighbor list (returned by `kim_get_neighbor_list `), the program will not take the energy contribution of atom 2 into account. So I have to find a way to get the 'correct' or 'actual' indices of neighbor atoms.

I have managed to solve this problem by comparing the fractional coordinates of atoms, but to do this, I have to code the lattice parameters into the driver. If there is not a subroutine that can do what I described, does `kim-api` provides a subroutine that returns the lattice parameters?

**Comment by ellio167** [comment]
Hi,
What you describe is consistent with the definitions of the KIM API standard.  (It is also not the way that most LAMMPS, and other simulators, perform their computations.)  Please read (at least) the [Theory](https://kim-api.readthedocs.io/en/latest/theory.html) section of the KIM API documentation and compare your definition of the atom energy and its derivatives to the definitions described there.

Once you have done that, please post any remaining questions you have here.

**Comment by meTchaikovsky** [comment]
Hi, 
I have read Theory and Implementation section, my understanding is KIM API starts from the atomistic configuration it received from LAMMPS,  and it does not care about what simulation box looks like, is it correct?

**Comment by ellio167** [comment]
Yes, that is correct.  The model driver should compute the energy and "partial forces" for that configuration as defined by the KIM API standard.  LAMMPS will then take those values and transform them appropriately to account for the periodic boundary conditions.

**Comment by meTchaikovsky** [comment]
Thank you, 

> LAMMPS will then take those values and transform them appropriately to account for the periodic boundary conditions.

This is truly helpful, I refactored my code and now it works fine without 'actual' ids.

**Comment by ellio167** [comment]
@meTchaikovsky ,

Great!  We'd love to have you submit your work to https://openkim.org when you have it completed!
