### ISSUE TITLE
*** ERROR *** Unable to successfully contact openkim.org to download models.

### ISSUE THREAD

**Issue by mkandes** [openkim/kim-api#25]
Hi OpenKIM team,

We're able to install single models with the kim-api-collections-management tool [1]. However, it fails when we attempt to install all of the models using the OpenKIM option [2]. It looks like it's failing on this wget for some reason [3]. Can you have a look when you get the chance?

Thanks,

Marty Kandes
SDSC HPC User Services Group

[1]

[mkandes@comet-ln2 bin]$ ./kim-api-collections-management install user SW_StillingerWeber_1985_Si__MO_405512056662_005
Downloading.............. SW_StillingerWeber_1985_Si__MO_405512056662_005
This item needs its driver 'SW__MD_335816936951_004', but it is not currently installed.
Trying to find it at openkim.org.
Downloading.............. SW__MD_335816936951_004
[100%] Built target SW__MD_335816936951_004
Install the project...
-- Install configuration: "Release"
-- Installing: /home/mkandes/.kim-api/model-drivers-dir/SW__MD_335816936951_004/libkim-api-model-driver.so
-- Set runtime path of "/home/mkandes/.kim-api/model-drivers-dir/SW__MD_335816936951_004/libkim-api-model-driver.so" to "/home/mkandes/Software/openkim/kim-api-2.0.2/install/lib64"
[100%] Built target SW_StillingerWeber_1985_Si__MO_405512056662_005
Install the project...
-- Install configuration: "Release"
-- Installing: /home/mkandes/.kim-api/models-dir/SW_StillingerWeber_1985_Si__MO_405512056662_005/libkim-api-model.so
-- Set runtime path of "/home/mkandes/.kim-api/models-dir/SW_StillingerWeber_1985_Si__MO_405512056662_005/libkim-api-model.so" to "/home/mkandes/Software/openkim/kim-api-2.0.2/install/lib64"

Success!
[mkandes@comet-ln2 bin]$

[2]

[mkandes@comet-ln2 bin]$ ./kim-api-collections-management install user OpenKIM
*** ERROR *** Unable to successfully contact openkim.org to download models.

Aborting!
[mkandes@comet-ln2 bin]$

[3]

# download item (and possibly its driver)
    if test x"OpenKIM" = x"${item_type}" -o x"OpenKIM_with_history" = x"${item_type}"; then
      local query='query={"type":{"$refex":"mo|sm"},"kim-api-version":{"$regex":"^'"${major_version}"'\\."}}'
      query="${query}"'&fields={"kimcode":1, "kim-api-version":1}'
      query="${query}"'&database=obj'
      if test x"OpenKIM_with_history" = x"${item_type}"; then
        query="${query}"'&history=on'
      fi
      local list
      list="`wget -q -O - --post-data="${query}" https://query.openkim.org/api`"
      if test $? -ne 0; then  # wget failed
        printf "*** ERROR *** Unable to successfully contact openkim.org to download models.\n"
        return 1
      fi
      list="`printf -- "%s" "${list}" | \
                     sed -e 's/\[//g' -e 's/\]//g' \
                     -e 's/{"kim-api-version": "\([0-9.]*\)", "kimcode": "\([^"]*\)"},*/\1:\2/g'`"
      for version in ${list}; do \
        if check_version_compatibility "${version}"; then
          local modname="`printf -- "%s" "${version}" | sed -e s/[^:]*://`"
          get_build_install_item "$install_collection" "${modname}" "${force}" "${use_sudo}" "${PASSWORD}" || return 1
        fi
      done
    else

**Comment by ellio167** [comment]
Hello,  Thanks for the report.

This is a known bug (https://groups.google.com/d/msg/openkim/p5_IAG0jHIs/1cPDHoQ0CAAJ)

This line https://github.com/openkim/kim-api/blob/44495c2a17f42bea72e60a0d58b12b176dd16f4a/utils/collections-management.in#L336

needs to have `refex` changed to `regex`, and then all should work fine.

The fix is already in the `devel` branch and will be included in the upcoming `kim-api-2.1.0` release (later this week).

[reopen if this doesn't fix all your problems.]
