### ISSUE TITLE
Build fails on i386 architecture: Error: Integer too big for its kind

### ISSUE THREAD

**Issue by yurivict** [openkim/kim-api#29]
http://beefy10.nyi.freebsd.org/data/112i386-default/506973/logs/kim-api-2.1.0.log

**Comment by ellio167** [comment]
@yurivict Thanks for the report.  I'll fix this and we'll make a bugfix release in a few days.

**Comment by yurivict** [comment]
In ```2.1.1``` the problem morphed into
```
/wrkdirs/usr/ports/science/kim-api/work/kim-api-2.1.1/fortran/include/kim_collections_module.f90:991:25:

  991 |         file_length = 2*(int(huge(dfile_length), c_long) + 1) &
      |                         1
```

http://beefy10.nyi.freebsd.org/data/112i386-default/507489/logs/kim-api-2.1.1.log

**Comment by ellio167** [comment]
Thanks,  I guess I didn't really fix it.  Will look for a better solution.
