### ISSUE TITLE
CMAKE: install() sane TAEGET default DESTINATIONS only available from > CMAKE v3.14

### ISSUE THREAD

**Issue by ellio167** [openkim/kim-api#41]
https://gitlab.kitware.com/cmake/cmake/-/commit/9fc20a4f3e1865e409d960c87e2e4a366775b72b

Need to fix for compatibility with CMAKE V3.4

https://github.com/openkim/kim-api/blob/26a26f42138783da55395cc94917726ce51d0c9c/CMakeLists.txt#L164

**Comment by ellio167** [comment]
@stukowski

**Comment by stukowski** [comment]
We probably have to change that line to
```
install(TARGETS kim-api 
  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
```
to make it work on all platforms and for all CMake versions.

**Comment by ellio167** [comment]
> We probably have to change that line to
> 
> ```
> install(TARGETS kim-api 
>   LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
>   ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
>   RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
> ```
> 
> to make it work on all platforms and for all CMake versions.

This works for me on macOS with cmake 3.14.  Can we confirm it works with Cygwin?

**Comment by stukowski** [comment]
Yes, I verified that it works with Cygwin + CMake 3.14 as well.
