### ISSUE TITLE
ENH: Extended parameter accessors

### ISSUE THREAD

**Issue by dskarls** [openkim/kim-api#74]
In the course of discussing the ASE merge request to supply methods to update portable model parameters using the calculator, [it was mentioned](https://gitlab.com/ase/ase/-/merge_requests/2267#note_497739417) that it would be nice not to have to figure out which indices you want to access/mutate in a given parameter array.  Would it make any sense to allow a model to define some sort of accessor method for its parameters that takes species as inputs?  For example, the Lennard-Jones model driver could provide a function that maps the pair "Al"-"Ni" to the relevant index in its `epsilons` and `sigmas` parameter arrays.

**Comment by ellio167** [comment]
I would be open to this if a workable general mechanism can be proposed that makes sense in the context of the kim-api’s very general concept of a model.  I don’t really see how such a thing can be invented, but I’ll be excited to be proved wrong.

**Comment by dskarls** [comment]
Is there another problem that I'm missing aside from the fact that the parameter arrays registered by a model can contain arbitrary content indexed in an arbitrary way?

**Comment by ellio167** [comment]
That's the main thing, I think.  I don't see any obvious way, other than numeric indices (or arbitrary strings, which doesn't really add any benefit) to organize/access a model's "parameters".

**Comment by ellio167** [comment]
Variadic functions are very tricky things to work with in a multi-language environment.  Fortran has nothing of the kind.  It's also impossible (in C/C++) to wrap a variadic function in another variadic function.

I'm not convinced that this is really easier for the user.  Certainly, this would need to be in-addition-to the existing index scheme.  Indexing, at least, has the advantage of being easy to systematically access/modify each/every parameter.

At this point the kim-api has a well-defined (index) method to access parameters.  This is sufficient, according to the principle of minimal completeness (e.g., https://martinfowler.com/bliki/MinimalInterface.html).  So, the proposed feature is going to need to demonstrate a pretty high bar of "added value" to convince me that it is a good idea to add to the kim-api.

**Comment by dskarls** [comment]
I guess without variadic functions, the accessors/mutators would instead probably have two arguments: the parameter name and a pointer to a (homogeneous) array that would contain the rest of the input "arguments".  I'm not even entirely sure that would work for fortran models.  Anyway, the minimal completeness argument is enough to defer this sort of thing to application-level code.  Closing (@gdonval feel free to re-open)
