### ISSUE TITLE
How to tell where configuration file is?

### ISSUE THREAD

**Issue by mhsiron** [openkim/kim-api#83]
When I try to run:
kim-api-collections-management install user SW_StillingerWeber_1985_Si__MO_405512056662_005

I get:
Invalid kim-api configuration file.
Aborting!

I have even removed the ~/.kim-api directory

How can I reset the configuration file?

**Comment by ellio167** [comment]
How have you installed the KIM-API?
If you know where the `kim-api-collections-info` utility is located (usually its in `PREFIX`/libexec/kim-api/), what is the result of `kim-api-collections-info config_file name`?

**Comment by mhsiron** [comment]
The command: 
`kim-api-collections-info config_file name` gave me a different file then the ~/.kim-api.

I went ahead and deleted the kim-config file.

After running the same command as before:
`kim-api-collections-management install user SW_StillingerWeber_1985_Si__MO_405512056662_005`

I get the same previous error:
`Invalid kim-api configuration file.
Aborting!`

I also noticed that the file was recreated. The file is empty.

I installed by directly compiling from source v2.3.0.

Thanks for your help!

**Comment by ellio167** [comment]
Can you please provide the cmake command line you used to build and install the kim-api?

**Comment by mhsiron** [comment]
I just followed what was in the install instruction (under for those who don't like to read):
 ```
mkdir build && cd build
 cmake .. -DCMAKE_BUILD_TYPE=Release
 make
```

Then, because I don't have root privilege, I set the environment variable DESTDIR to a place where the binaries could be installed

 `make install`

Finally, I added the bin folder to the PATH and the lib64 folder to the LD_LIRBARY_PATH.

I am on an OpenSUSE system.

**Comment by ellio167** [comment]
Ah ha!

That will certainly lead to problems....

You should use the PREFIX mechanism:

```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<value of your DESTDIR>
make
make install
```

Then you also won't need to set LD_LIBRARY_PATH and you can use 
```
source <PREFIX>/bin/kim-api-activate
```
in your shell configuration file to set up PATH and a few other env vars helpfully.

**Comment by mhsiron** [comment]
I just repeated the steps you mentioned in a clean environment and it resulted in the same error :(

**Comment by mhsiron** [comment]
Update -- I fixed the error by running: 

`kim-api-collections-info write_config_file file_path dir1_path dir2_path dir3_path`

**Comment by mhsiron** [comment]
Now -- my next error is a wget error 4 when "kim-api-collections-management install user SW_StillingerWeber_1985_Si__MO_405512056662_005" unsure if this is related?

**Comment by ellio167** [comment]
I'm also not sure why you needed to do the `kim-api-collections-info` step...

The wget error code 4 is a network failure.

Yes, if you download and untar the archive (you'll also need the driver archive) you can install it with the same command line but instead of just the model name you give the path to the code directory.  Still it might be simpler to get the network setup on the machine...

**Comment by mhsiron** [comment]
All is good with a manual install -- I am still unsure why I needed the kim-api-collections-info, but at least my issues have been resolved. Happy to close this issue!
