### ISSUE TITLE
basic instructions for installing from source without sudo

### ISSUE THREAD

**Issue by bernstei** [openkim/kim-api#87]
As lots of people installing the kim api are likely to be doing it on linux servers, I don't think it's reasonable to expect them to be able to sudo, as the instructions appear to require https://openkim.org/doc/usage/obtaining-models/#installing_api

Is there any way that this can be done without the sudo?

**Comment by ellio167** [comment]
In this case the user needs to install into a non-system path using an installation prefix.  Instructions can be found here:

https://github.com/openkim/kim-api/blob/431e641788a5df5ff6058e1974004c7efe93931e/INSTALL#L371
```
D.2.3 INSTALLATION PREFIX

Here and below, all paths or filepaths must be specified in a format
appropriate for the OS (windows or linux).  Windows paths are of the form
C:\dir1\dir2 (forward slashes may be used instead to avoid escaping issues:
C:/dir1/dir2) and linux paths are of the form /dir1/dir2.

By default CMake installs the KIM API package under the Global prefix
"/usr/local".  This is referred to as a "Global" (or system-wide) installation.
It is available to all users of the system.  (Other "Global" prefix values are
"/" and "/usr".)  However, such installations require root user permissions (as
implied by the use of the "sudo" command above).  If you do not have root user
permission and/or do not want to install the KIM API to the global location,
you can change where CMake installs the KIM API by replacing the command (from
above)

   $ cmake .. -DCMAKE_BUILD_TYPE=Release

with

   $ cmake .. -DCMAKE_INSTALL_PREFIX="/install/prefix/path" -DCMAKE_BUILD_TYPE=Release

where "/install/prefix/path" should be replaced with your desired prefix.  For
example, to install the KIM API in the "local" subdirectory of your home
directory, use "${HOME}/local".  When installed in such a directory, the user
may employ the "kim-api-activate" utility to setup the PATH and bash
completions.  For example:

   $ source ${HOME}/local/bin/kim-api-activate
```

**Comment by bernstei** [comment]
And you don't think this procedure should be in the basic web instructions? I think that assuming that users are doing this from an admin-capable account is a bad assumption.

**Comment by ellio167** [comment]
It depends on who is the intended audience of the documentation.  The current documentation is written for sys admins and assumes enough knowledge of linux software installation conventions that a need for the PREFIX settings would be understood.

If it is expected that typical linux system users will be installing from source, then I agree, the documentation should be update/rewritten to address that audience.
